;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        color-occur-next
        color-occur-prev
        dabbrev-expand
        indent-new-comment-line
        kill-region
        next-error
        orgtbl-self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-unwrap-sexp
        sp-delete-char
        sp-forward-slurp-sexp
        undo
        ))

(setq mc/cmds-to-run-once
      '(
        pp-eval-expression
        ))
