(add-to-list 'load-path "~/.emacs.d/dash.el/")
(require 'dash)
(setq magit-auto-revert-mode nil)
(setq magit-last-seen-setup-instructions "1.4.0")
(add-to-list 'load-path "~/.emacs.d/magit")
(require 'magit)
(setq magit-auto-revert-mode nil)
