;; -*- emacs-lisp -*-
;; Tramp connection history.  Don't change this file.
;; You can delete it, forcing Tramp to reapply the checks.

((["scp" "artem" "dev03" nil]
  ("uname" "Linux 2.6.32-30-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("ls" "/bin/ls --color=never")
  ("ls-dired" t)
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d"))
 (["scp" nil "dev03" nil]
  ("uname" "Linux 2.6.32-30-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("ls" "/bin/ls --color=never")
  ("ls-dired" t)
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("readlink" "\\readlink")
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d")
  ("~" "/home/artem")
  ("uid-integer" 1051))
 (["scp" nil "dev03.factual.com" nil]
  ("uname" "Linux 2.6.32-30-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("file-exists" "test -e")
  ("uid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d")
  ("~" "/home/artem")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("ls" "/bin/ls --color=never")
  ("ls-dired" t))
 (["scp" nil "dev04.factual.com" nil]
  ("uname" "Linux 2.6.32-31-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("file-exists" "test -e")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d"))
 (["scpx" "artem" "dev04.factual.com" nil]
  ("uname" "Linux 2.6.32-31-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("file-exists" "test -e")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d"))
 (["scpx" nil "dev03.factual.com" nil]
  ("uname" "Linux 2.6.32-30-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("file-exists" "test -e")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d"))
 (["pscp" nil "dev03.factual.com" nil]
  ("uname" "Darwin 11.4.0")
  ("test" "test")
  ("remote-path"
   ("/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("readlink" nil)
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("stat" nil)
  ("~" "/Users/artem"))
 (["rsync" nil "dev03.factual.com" nil]
  ("uname" "Linux 2.6.32-30-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d"))
 (["ssh" nil "dev04.factual.com" nil]
  ("uname" "Linux 2.6.32-31-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/bash")
  ("file-exists" "test -e")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d")
  ("uid-integer" 1051)
  ("ls" "/bin/ls --color=never"))
 (["ssh" nil "dev101" nil]
  ("uname" "Linux 3.2.0-24-generic")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/bash")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("stat" "\\stat")
  ("file-exists" "test -e")
  ("readlink" "\\readlink")
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d")
  ("uid-integer" 1051)
  ("ls" "/bin/ls --color=never")
  ("ls-dired" t))
 (["ssh" nil "dev102" nil]
  ("uname" "Linux 3.2.0-24-generic")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/bash")
  ("file-exists" "test -e")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1051)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d")
  ("uid-integer" 1051))
 (["ssh" nil "192.168.0.6" nil]
  ("uname" "Linux 2.6.38-12-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/bash")
  ("~" "/home/artem")
  ("file-exists" "test -e")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("ls" "/bin/ls --color=never")
  ("ls-dired" t)
  ("stat" "\\stat")
  ("id" "/usr/bin/id")
  ("gid-integer" 1000)
  ("readlink" "\\readlink")
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i"))
 (["ssh" nil "stuph.co#24" nil]
  ("uname" "Linux 2.6.38-12-server")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/usr/sbin" "/usr/local/bin"))
  ("remote-shell" "/bin/bash")
  ("file-exists" "test -e")
  ("readlink" "\\readlink")
  ("stat" "\\stat")
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("ls" "/bin/ls --color=never")
  ("ls-dired" t)
  ("id" "/usr/bin/id")
  ("gid-integer" 1000)
  ("local-encoding" base64-encode-region)
  ("local-decoding" base64-decode-region)
  ("remote-encoding" "base64")
  ("remote-decoding" "base64 -d -i")
  ("uid-integer" 1000)
  ("inline-compress" "gzip")
  ("inline-decompress" "gzip -d")))
